### PR TITLE
Migrated code from .NET Core 2.0 to 3.1

### PR DESCRIPTION
**Pull request by abirroy2911**
Migrated code from .NET Core 2.0 to 3.1

### CODE REVIEW

**Comment by krishnamhn009** [comment]
looks good..merging this in master branch

**Comment by krishnamhn009** [comment]
@go2ismail are you looking into pr!!

**Comment by arunkumarmpk** [comment]
is this commit merged to master?

**Comment by krishnamhn009** [comment]
not yet..this can be done repo owner only

**Comment by go2ismail** [comment]
see newer .NET 8.0 version

**Pull request closed without merging**
